import { NextResponse } from 'next/server';
import dbConnect from '@/lib/mongoose';
import Client from '@/models/Client';
import RetentionTask from '@/models/RetentionTask';

export async function POST(request: Request) {
    try {
        await dbConnect();
        const body = await request.json();
        const tasks = Array.isArray(body.data) ? body.data : body.tasks;

        if (!Array.isArray(tasks)) {
            return NextResponse.json({ error: 'Invalid input' }, { status: 400 });
        }

        // Extract all unique legacyIds from CSV (trimmed)
        const legacyIds = [...new Set(
            tasks
                .map((t: any) => (t.clientid || t.client || t.clientId || t.legacyId || t.clientLegacyId || '').toString().trim())
                .filter(Boolean)
        )];

        // Batch-fetch all matching clients
        const clients = await Client.find({ legacyId: { $in: legacyIds } })
            .select('_id legacyId')
            .lean();

        const legacyToId = new Map<string, string>();
        clients.forEach((c: any) => {
            legacyToId.set(c.legacyId.toString().trim(), c._id.toString());
        });

        let insertedCount = 0;
        const missingLegacyIds: string[] = [];
        const toInsert: any[] = [];

        for (const item of tasks) {
            const rawClientId = (item.clientid || item.client || item.clientId || item.legacyId || item.clientLegacyId || '').toString().trim();
            if (!rawClientId) continue;

            const clientObjectId = legacyToId.get(rawClientId);
            if (!clientObjectId) {
                if (!missingLegacyIds.includes(rawClientId)) {
                    missingLegacyIds.push(rawClientId);
                }
                continue;
            }

            const parseDate = (val: string | undefined) => {
                if (!val) return undefined;
                const d = new Date(val);
                return isNaN(d.getTime()) ? undefined : d;
            };

            toInsert.push({
                client: clientObjectId,
                task: item.task || '',
                type: item.type || 'Followup Call',
                priority: item.priority || 'Medium',
                assignedTo: item.assignedTo || '',
                autoGenerated: item.autoGenerated === 'true' || item.autoGenerated === true,
                triggerReason: item.triggerReason || '',
                notes: item.notes || '',
                status: item.status || 'To Do',
                dueDate: parseDate(item.dueDate),
                nextFollowupDate: parseDate(item.nextFollowupDate),
                completionDate: parseDate(item.completionDate),
                createdBy: item.createdBy || 'Import',
                createdAt: parseDate(item.createdAt) || new Date(),
                updatedAt: parseDate(item.updatedAt) || new Date()
            });
        }

        // Bulk insert in batches of 5000
        const BATCH_SIZE = 5000;
        for (let i = 0; i < toInsert.length; i += BATCH_SIZE) {
            const batch = toInsert.slice(i, i + BATCH_SIZE);
            await RetentionTask.insertMany(batch, { ordered: false });
        }
        insertedCount = toInsert.length;

        if (missingLegacyIds.length > 0) {
            console.log('Missing client legacyIds for tasks:', missingLegacyIds);
        }

        return NextResponse.json({
            message: 'Import completed',
            count: insertedCount,
            missingClients: missingLegacyIds.length,
            missingClientIds: missingLegacyIds.slice(0, 50),
            totalProcessed: tasks.length
        });
    } catch (error: any) {
        console.error("Import Tasks Error:", error);
        return NextResponse.json({ error: error.message }, { status: 500 });
    }
}
