'use client';

import React, { useState, useEffect, useCallback, useRef } from 'react';
import ReactDOM from 'react-dom';
import {
    Phone,
    Mail,
    Calendar,
    Clock,
    User,
    AlertTriangle,
    CheckCircle2,
    Zap,
    TrendingUp,
    Target,
    Plus,
    RefreshCw,
    MessageSquare,
    PhoneCall,
    Loader2,
    X,
    PlayCircle,
    GripVertical,
    SkipForward,
    DollarSign,
    Activity,
    ShieldCheck,
    Snowflake,
    HeartCrack,
    Search,
    ListTodo,
    Eye
} from 'lucide-react';
import { cn } from '@/lib/utils';
import toast from 'react-hot-toast';
import { useRouter } from 'next/navigation';

interface Task {
    _id: string;
    client: string;
    clientInfo?: {
        _id: string;
        name: string;
        phones?: { value: string; label: string }[];
        emails?: { value: string; label: string }[];
    };
    type: string;
    task?: string;
    status: 'To Do' | 'In Progress' | 'In Review' | 'Ignored' | 'Completed';
    priority: 'Low' | 'Medium' | 'High' | 'Critical';
    dueDate: string;
    assignedTo?: string;
    assignedToInfo?: { _id: string; firstName: string; lastName: string };
    notes?: string;
    outcome?: string;
    autoGenerated?: boolean;
    triggerReason?: string;
    createdAt: string;
    completedAt?: string;
}

interface Client {
    _id: string;
    name: string;
    contactStatus?: string;
    contactType?: string;
    totalRevenue?: number;
    balance?: number;
    activityCount?: number;
    lastActivity?: string;
    phones?: { value: string; label: string }[];
    emails?: { value: string; label: string }[];
}

type KanbanColumn = 'To Do' | 'In Progress' | 'In Review' | 'Completed';

const COLUMNS: { id: KanbanColumn; label: string; color: string; bgColor: string; icon: React.ReactNode }[] = [
    { id: 'To Do', label: 'TO DO', color: 'text-amber-600', bgColor: 'bg-amber-50 border-amber-200', icon: <Clock className="w-4 h-4" /> },
    { id: 'In Progress', label: 'IN PROGRESS', color: 'text-blue-600', bgColor: 'bg-blue-50 border-blue-200', icon: <PlayCircle className="w-4 h-4" /> },
    { id: 'In Review', label: 'IN REVIEW', color: 'text-purple-600', bgColor: 'bg-purple-50 border-purple-200', icon: <Eye className="w-4 h-4" /> },
    { id: 'Completed', label: 'DONE', color: 'text-emerald-600', bgColor: 'bg-emerald-50 border-emerald-200', icon: <CheckCircle2 className="w-4 h-4" /> },
];

const priorityColors = {
    Low: 'border-l-slate-300',
    Medium: 'border-l-blue-500',
    High: 'border-l-orange-500',
    Critical: 'border-l-red-500'
};

const typeIcons: { [key: string]: React.ReactNode } = {
    'Followup Call': <PhoneCall className="w-3.5 h-3.5" />,
    'Followup Email': <Mail className="w-3.5 h-3.5" />,
    'Check-in': <MessageSquare className="w-3.5 h-3.5" />,
    'Re-engagement': <RefreshCw className="w-3.5 h-3.5" />,
    'Win-back': <Target className="w-3.5 h-3.5" />,
    'Feedback Request': <MessageSquare className="w-3.5 h-3.5" />,
    'Upsell Opportunity': <TrendingUp className="w-3.5 h-3.5" />
};

const TASKS_PER_PAGE = 10;

export default function TasksPage() {
    const router = useRouter();
    const [search, setSearch] = useState('');
    const [generating, setGenerating] = useState(false);
    const [users, setUsers] = useState<{ _id: string; firstName: string; lastName: string }[]>([]);
    const [clients, setClients] = useState<Client[]>([]);

    // Per-column state
    const [columnTasks, setColumnTasks] = useState<Record<KanbanColumn, Task[]>>({
        'To Do': [], 'In Progress': [], 'In Review': [], 'Completed': []
    });
    const [columnPages, setColumnPages] = useState<Record<KanbanColumn, number>>({
        'To Do': 1, 'In Progress': 1, 'In Review': 1, 'Completed': 1
    });
    const [columnTotals, setColumnTotals] = useState<Record<KanbanColumn, number>>({
        'To Do': 0, 'In Progress': 0, 'In Review': 0, 'Completed': 0
    });
    const [columnLoading, setColumnLoading] = useState<Record<KanbanColumn, boolean>>({
        'To Do': false, 'In Progress': false, 'In Review': false, 'Completed': false
    });
    const [initialLoading, setInitialLoading] = useState(true);

    // Status counts from aggregation (real totals)
    const [statusCounts, setStatusCounts] = useState<Record<string, number>>({});

    // Drag state
    const [draggedTask, setDraggedTask] = useState<Task | null>(null);
    const [dragOverColumn, setDragOverColumn] = useState<KanbanColumn | null>(null);

    // Modal
    const [isModalOpen, setIsModalOpen] = useState(false);
    const [selectedTask, setSelectedTask] = useState<Task | null>(null);
    const [outcomeText, setOutcomeText] = useState('');
    const [isSubmitting, setIsSubmitting] = useState(false);

    // New Task Modal
    const [isNewTaskModalOpen, setIsNewTaskModalOpen] = useState(false);
    const [newTask, setNewTask] = useState({
        client: '',
        type: 'Check-in',
        priority: 'Medium',
        dueDate: new Date().toISOString().split('T')[0],
        assignedTo: '',
        notes: ''
    });

    // Header portal
    const [portalTarget, setPortalTarget] = useState<HTMLElement | null>(null);
    useEffect(() => {
        const el = document.getElementById('header-portal-target');
        if (el) setPortalTarget(el);
    }, []);

    // Fetch tasks for a specific column
    const fetchColumnTasks = useCallback(async (status: KanbanColumn, page: number, append = false) => {
        setColumnLoading(prev => ({ ...prev, [status]: true }));
        try {
            const params = new URLSearchParams({
                status,
                page: String(page),
                limit: String(TASKS_PER_PAGE),
                ...(search && { search })
            });
            const res = await fetch(`/api/crm/retention?${params}`);
            const data = await res.json();

            if (data.statusCounts) {
                setStatusCounts(data.statusCounts);
            }

            setColumnTasks(prev => {
                const newTasks = data.tasks || [];
                if (append) {
                    const merged = [...prev[status], ...newTasks];
                    // Deduplicate by _id
                    const seen = new Set<string>();
                    const deduped = merged.filter((t: Task) => {
                        if (seen.has(t._id)) return false;
                        seen.add(t._id);
                        return true;
                    });
                    return { ...prev, [status]: deduped };
                }
                return { ...prev, [status]: newTasks };
            });
            setColumnTotals(prev => ({ ...prev, [status]: data.total || 0 }));
            setColumnPages(prev => ({ ...prev, [status]: page }));
        } catch (error) {
            console.error(`Error fetching ${status} tasks:`, error);
        } finally {
            setColumnLoading(prev => ({ ...prev, [status]: false }));
        }
    }, [search]);

    // Initial load: fetch all columns
    const fetchAllColumns = useCallback(async () => {
        setInitialLoading(true);
        await Promise.all(COLUMNS.map(col => fetchColumnTasks(col.id, 1, false)));
        setInitialLoading(false);
    }, [fetchColumnTasks]);

    useEffect(() => {
        fetchAllColumns();
        fetchUsers();
        fetchClients();
    }, []);

    // Re-fetch when search changes
    useEffect(() => {
        const timer = setTimeout(() => {
            fetchAllColumns();
        }, 300);
        return () => clearTimeout(timer);
    }, [search]);

    const fetchUsers = async () => {
        try {
            const res = await fetch('/api/users?limit=100');
            const data = await res.json();
            setUsers(data.users || []);
        } catch (e) {
            console.error('Failed to fetch users', e);
        }
    };

    const fetchClients = async () => {
        try {
            const res = await fetch('/api/clients?limit=500');
            const data = await res.json();
            setClients(data.clients || []);
        } catch (e) {
            console.error('Failed to fetch clients', e);
        }
    };

    const handleAutoGenerate = async () => {
        try {
            setGenerating(true);
            const res = await fetch('/api/crm/retention/auto-generate', { method: 'POST' });
            const data = await res.json();
            toast.success(`Created ${data.tasksCreated} tasks (${data.tasksAssigned} auto-assigned)`);
            fetchAllColumns();
        } catch (error) {
            console.error('Auto-generate error:', error);
            toast.error('Failed to generate tasks');
        } finally {
            setGenerating(false);
        }
    };

    const handleUpdateTask = async (taskId: string, updates: Partial<Task>) => {
        try {
            const res = await fetch(`/api/crm/retention/${taskId}`, {
                method: 'PATCH',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(updates)
            });
            if (res.ok) return true;
            return false;
        } catch (error) {
            console.error('Update error:', error);
            return false;
        }
    };

    // Load more for a column
    const handleLoadMore = (status: KanbanColumn) => {
        const nextPage = columnPages[status] + 1;
        fetchColumnTasks(status, nextPage, true);
    };

    // Drag & Drop Handlers
    const handleDragStart = (e: React.DragEvent, task: Task) => {
        setDraggedTask(task);
        e.dataTransfer.effectAllowed = 'move';
        e.dataTransfer.setData('text/plain', task._id);
    };

    const handleDragOver = (e: React.DragEvent, column: KanbanColumn) => {
        e.preventDefault();
        e.dataTransfer.dropEffect = 'move';
        setDragOverColumn(column);
    };

    const handleDragLeave = () => {
        setDragOverColumn(null);
    };

    const handleDrop = async (e: React.DragEvent, targetColumn: KanbanColumn) => {
        e.preventDefault();
        setDragOverColumn(null);

        if (!draggedTask || draggedTask.status === targetColumn) {
            setDraggedTask(null);
            return;
        }

        const previousStatus = draggedTask.status;

        // Remove from source column, add to target column
        setColumnTasks(prev => ({
            ...prev,
            [previousStatus]: prev[previousStatus as KanbanColumn].filter(t => t._id !== draggedTask._id),
            [targetColumn]: [{ ...draggedTask, status: targetColumn }, ...prev[targetColumn]]
        }));

        const updates: Partial<Task> = { status: targetColumn };
        if (targetColumn === 'Completed') {
            updates.completedAt = new Date().toISOString();
        }

        const success = await handleUpdateTask(draggedTask._id, updates);
        
        if (!success) {
            // Revert on failure
            setColumnTasks(prev => ({
                ...prev,
                [previousStatus]: [{ ...draggedTask, status: previousStatus as any }, ...prev[previousStatus as KanbanColumn]],
                [targetColumn]: prev[targetColumn].filter(t => t._id !== draggedTask._id)
            }));
            toast.error('Failed to move task');
        } else {
            toast.success(`Task moved to ${targetColumn}`);
            // Refresh counts
            fetchColumnTasks(previousStatus as KanbanColumn, 1, false);
            fetchColumnTasks(targetColumn, 1, false);
        }

        setDraggedTask(null);
    };

    const handleDragEnd = () => {
        setDraggedTask(null);
        setDragOverColumn(null);
    };

    const handleCompleteTask = async () => {
        if (!selectedTask) return;
        setIsSubmitting(true);
        const success = await handleUpdateTask(selectedTask._id, {
            status: 'Completed',
            outcome: outcomeText
        });
        if (success) {
            toast.success('Task completed');
            setIsModalOpen(false);
            setSelectedTask(null);
            setOutcomeText('');
            fetchAllColumns();
        } else {
            toast.error('Failed to complete task');
        }
        setIsSubmitting(false);
    };

    const handleCreateTask = async (e: React.FormEvent) => {
        e.preventDefault();
        setIsSubmitting(true);
        try {
            const res = await fetch('/api/crm/retention', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(newTask)
            });
            if (res.ok) {
                toast.success('Task created');
                setIsNewTaskModalOpen(false);
                setNewTask({
                    client: '',
                    type: 'Check-in',
                    priority: 'Medium',
                    dueDate: new Date().toISOString().split('T')[0],
                    assignedTo: '',
                    notes: ''
                });
                fetchAllColumns();
            } else {
                toast.error('Failed to create task');
            }
        } catch (error) {
            toast.error('Error creating task');
        } finally {
            setIsSubmitting(false);
        }
    };

    const openTaskModal = (task: Task) => {
        setSelectedTask(task);
        setOutcomeText(task.outcome || '');
        setIsModalOpen(true);
    };

    const formatDate = (dateStr: string) => {
        if (!dateStr) return 'No date';
        const date = new Date(dateStr);
        if (isNaN(date.getTime())) return 'Invalid Date';
        const today = new Date();
        today.setHours(0, 0, 0, 0);
        const taskDate = new Date(dateStr);
        taskDate.setHours(0, 0, 0, 0);

        const diff = Math.floor((taskDate.getTime() - today.getTime()) / (1000 * 60 * 60 * 24));

        if (diff < 0) return `${Math.abs(diff)}d overdue`;
        if (diff === 0) return 'Today';
        if (diff === 1) return 'Tomorrow';
        return date.toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
    };

    const isOverdue = (task: Task) => {
        return (task.dueDate && new Date(task.dueDate) < new Date(new Date().setHours(0, 0, 0, 0)) && task.status !== 'Completed' && task.status !== 'Ignored');
    };

    const getColumnCount = (columnId: KanbanColumn) => {
        return statusCounts[columnId] || 0;
    };

    // Header Portal Content
    const headerContent = (
        <div className="flex items-center justify-between w-full h-full px-4">
            <div className="flex items-center space-x-4">
                <h1 className="text-sm font-bold text-foreground uppercase tracking-tight">Tasks</h1>
                <div className="relative group">
                    <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-muted-foreground group-focus-within:text-primary transition-colors" />
                    <input 
                        type="text" 
                        placeholder="Search by client..."
                        value={search}
                        onChange={(e) => setSearch(e.target.value)}
                        className="pl-8 pr-4 h-7 w-52 bg-background border border-border text-[11px] focus:outline-none focus:ring-1 focus:ring-primary/5 transition-all placeholder:text-muted-foreground text-foreground rounded"
                    />
                </div>
            </div>

            <div className="flex items-center space-x-2">
                <button
                    onClick={handleAutoGenerate}
                    disabled={generating}
                    className="flex items-center space-x-1.5 px-3 h-7 text-[10px] font-bold text-primary-foreground bg-primary border border-primary/20 rounded hover:opacity-90 transition-all uppercase tracking-wide disabled:opacity-50 shadow-sm cursor-pointer"
                >
                    {generating ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Zap className="w-3.5 h-3.5" />}
                    <span>Auto-Generate</span>
                </button>
                
                <button
                    onClick={() => setIsNewTaskModalOpen(true)}
                    className="flex items-center justify-center h-7 w-7 bg-card border border-border text-foreground hover:bg-secondary rounded shadow-sm transition-all cursor-pointer"
                    title="New Task"
                >
                    <Plus className="w-4 h-4" />
                </button>
            </div>
        </div>
    );

    return (
        <div className="flex flex-col h-[calc(100vh-48px)] bg-background transition-colors duration-300 overflow-hidden">
            {/* Portal header actions */}
            {portalTarget && ReactDOM.createPortal(headerContent, portalTarget)}

            <div className="flex-1 overflow-x-auto p-1">
                {initialLoading ? (
                    <div className="flex items-center justify-center h-full">
                        <Loader2 className="w-8 h-8 animate-spin text-slate-400" />
                    </div>
                ) : (
                    <div className="flex space-x-4 h-full min-w-max">
                        {COLUMNS.map((column) => {
                            const tasks = columnTasks[column.id];
                            const total = getColumnCount(column.id);
                            const hasMore = tasks.length < columnTotals[column.id];
                            const isLoading = columnLoading[column.id];

                            return (
                                <div
                                    key={column.id}
                                    className={cn(
                                        "flex flex-col w-[360px] bg-secondary/30 border border-border shadow-sm h-full transition-all rounded-lg overflow-hidden",
                                        dragOverColumn === column.id && "ring-2 ring-primary ring-offset-2"
                                    )}
                                    onDragOver={(e) => handleDragOver(e, column.id)}
                                    onDragLeave={handleDragLeave}
                                    onDrop={(e) => handleDrop(e, column.id)}
                                >
                                    {/* Column Header */}
                                    <div className={cn("px-4 py-3 border-b border-border flex items-center justify-between shrink-0 bg-background/50")}>
                                        <div className="flex items-center space-x-2">
                                            <span className={column.color}>{column.icon}</span>
                                            <span className={cn("text-xs font-black uppercase tracking-wider text-foreground")}>{column.label}</span>
                                        </div>
                                        <span className={cn("text-sm font-black text-muted-foreground/50")}>{total}</span>
                                    </div>

                                    {/* Column Content */}
                                    <div className="flex-1 overflow-y-auto p-3 space-y-2 scrollbar-custom">
                                        {tasks.length === 0 && !isLoading ? (
                                            <div className="flex flex-col items-center justify-center py-8 text-slate-400">
                                                <div className="w-12 h-12 bg-slate-100 flex items-center justify-center mb-2">
                                                    {column.icon}
                                                </div>
                                                <p className="text-[10px] font-bold uppercase">No tasks</p>
                                            </div>
                                        ) : (
                                            <>
                                                {tasks.map((task) => (
                                                    <div
                                                        key={task._id}
                                                        draggable
                                                        onDragStart={(e) => handleDragStart(e, task)}
                                                        onDragEnd={handleDragEnd}
                                                        onClick={() => openTaskModal(task)}
                                                        className={cn(
                                                            "bg-background border border-border border-l-4 p-3 cursor-grab active:cursor-grabbing hover:shadow-lg transition-all group rounded hover:scale-[1.02] transform transition-transform duration-200",
                                                            priorityColors[task.priority],
                                                            draggedTask?._id === task._id && "opacity-50 scale-95",
                                                            isOverdue(task) && "bg-destructive/5"
                                                        )}
                                                    >
                                                        {/* Task Header */}
                                                        <div className="flex items-start justify-between mb-2">
                                                            <div className="flex items-center space-x-2">
                                                                <div className={cn(
                                                                    "w-6 h-6 flex items-center justify-center",
                                                                    task.priority === 'Critical' ? "bg-red-100 text-red-600" :
                                                                    task.priority === 'High' ? "bg-orange-100 text-orange-600" :
                                                                    task.priority === 'Medium' ? "bg-blue-100 text-blue-600" :
                                                                    "bg-slate-100 text-slate-600"
                                                                )}>
                                                                    {typeIcons[task.type] || <Target className="w-3 h-3" />}
                                                                </div>
                                                                <span className="text-[10px] font-bold text-slate-600 uppercase">{task.type}</span>
                                                            </div>
                                                            <GripVertical className="w-4 h-4 text-slate-300 opacity-0 group-hover:opacity-100 transition-opacity" />
                                                        </div>

                                                        {/* Client Name */}
                                                        <div className="text-sm font-bold text-foreground mb-2 truncate">
                                                            {task.clientInfo?.name || 'Unknown Client'}
                                                        </div>

                                                        {/* Notes Preview */}
                                                        {task.notes && (
                                                            <p className="text-[10px] text-slate-500 line-clamp-2 mb-2">{task.notes}</p>
                                                        )}

                                                        {/* Auto-generated badge */}
                                                        {task.autoGenerated && (
                                                            <div className="flex items-center space-x-1 mb-2">
                                                                <Zap className="w-2.5 h-2.5 text-orange-500" />
                                                                <span className="text-[9px] font-bold text-orange-600 uppercase">{task.triggerReason}</span>
                                                            </div>
                                                        )}

                                                        {/* Footer */}
                                                        <div className="flex items-center justify-between pt-2 border-t border-border">
                                                            <div className="flex items-center space-x-1">
                                                                <Calendar className="w-3 h-3 text-slate-400" />
                                                                <span className={cn(
                                                                    "text-[10px] font-bold",
                                                                    isOverdue(task) ? "text-red-600" : "text-slate-500"
                                                                )}>
                                                                    {formatDate(task.dueDate)}
                                                                </span>
                                                            </div>
                                                            {task.assignedToInfo && (
                                                                <div className="flex items-center space-x-1">
                                                                    <div className="w-5 h-5 bg-slate-200 flex items-center justify-center text-[8px] font-black text-slate-600">
                                                                        {task.assignedToInfo.firstName?.charAt(0)}
                                                                    </div>
                                                                </div>
                                                            )}
                                                        </div>
                                                    </div>
                                                ))}

                                                {/* Load More Button */}
                                                {hasMore && (
                                                    <button
                                                        onClick={(e) => { e.stopPropagation(); handleLoadMore(column.id); }}
                                                        disabled={isLoading}
                                                        className="w-full py-2 text-[10px] font-bold uppercase text-muted-foreground hover:text-foreground hover:bg-secondary/50 border border-dashed border-border rounded transition-all cursor-pointer"
                                                    >
                                                        {isLoading ? (
                                                            <Loader2 className="w-3.5 h-3.5 animate-spin mx-auto" />
                                                        ) : (
                                                            `Load More (${tasks.length}/${columnTotals[column.id]})`
                                                        )}
                                                    </button>
                                                )}
                                            </>
                                        )}
                                    </div>
                                </div>
                            );
                        })}
                    </div>
                )}
            </div>

            {/* Task Detail Modal */}
            {isModalOpen && selectedTask && (
                <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm p-4">
                    <div className="bg-white w-full max-w-lg shadow-2xl animate-in fade-in zoom-in duration-200">
                        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-100">
                            <div className="flex items-center space-x-3">
                                <div className={cn(
                                    "w-10 h-10 flex items-center justify-center",
                                    selectedTask.priority === 'Critical' ? "bg-red-100 text-red-600" :
                                    selectedTask.priority === 'High' ? "bg-orange-100 text-orange-600" :
                                    selectedTask.priority === 'Medium' ? "bg-blue-100 text-blue-600" :
                                    "bg-slate-100 text-slate-600"
                                )}>
                                    {typeIcons[selectedTask.type] || <Target className="w-5 h-5" />}
                                </div>
                                <div>
                                    <h2 className="text-sm font-black uppercase tracking-widest text-slate-900">{selectedTask.type}</h2>
                                    <span className={cn(
                                        "text-[9px] font-bold uppercase px-2 py-0.5",
                                        selectedTask.priority === 'Critical' ? "bg-red-100 text-red-700" :
                                        selectedTask.priority === 'High' ? "bg-orange-100 text-orange-700" :
                                        selectedTask.priority === 'Medium' ? "bg-blue-100 text-blue-700" :
                                        "bg-slate-100 text-slate-600"
                                    )}>
                                        {selectedTask.priority} Priority
                                    </span>
                                </div>
                            </div>
                            <button onClick={() => setIsModalOpen(false)} className="text-slate-400 hover:text-black">
                                <X className="w-5 h-5" />
                            </button>
                        </div>

                        <div className="p-6 space-y-4">
                            {/* Client Info */}
                            <div className="flex items-center space-x-3 p-3 bg-secondary/30 border border-border rounded">
                                <div className="w-12 h-12 bg-secondary flex items-center justify-center text-sm font-black text-muted-foreground rounded">
                                    {selectedTask.clientInfo?.name?.charAt(0) || '?'}
                                </div>
                                <div className="flex-1">
                                    <div className="text-sm font-bold text-foreground">{selectedTask.clientInfo?.name || 'Unknown'}</div>
                                    <div className="flex items-center space-x-3 text-[11px] text-muted-foreground mt-1">
                                        {selectedTask.clientInfo?.phones?.[0]?.value && (
                                            <a href={`tel:${selectedTask.clientInfo.phones[0].value}`} className="flex items-center hover:text-primary">
                                                <Phone className="w-3 h-3 mr-1" />{selectedTask.clientInfo.phones[0].value}
                                            </a>
                                        )}
                                        {selectedTask.clientInfo?.emails?.[0]?.value && (
                                            <a href={`mailto:${selectedTask.clientInfo.emails[0].value}`} className="flex items-center hover:text-primary">
                                                <Mail className="w-3 h-3 mr-1" />{selectedTask.clientInfo.emails[0].value}
                                            </a>
                                        )}
                                    </div>
                                </div>
                                <button
                                    onClick={() => router.push(`/crm/clients/${selectedTask.client}`)}
                                    className="px-3 py-1.5 bg-primary text-black text-[10px] font-bold uppercase hover:opacity-90 rounded cursor-pointer"
                                >
                                    View Profile
                                </button>
                            </div>

                            {/* Assigned To */}
                            {selectedTask.assignedToInfo && (
                                <div className="flex items-center space-x-2">
                                    <User className="w-4 h-4 text-slate-400" />
                                    <span className="text-xs text-slate-500">Assigned to:</span>
                                    <span className="text-xs font-bold text-slate-700">
                                        {selectedTask.assignedToInfo.firstName} {selectedTask.assignedToInfo.lastName}
                                    </span>
                                </div>
                            )}

                            {/* Details */}
                            <div className="grid grid-cols-2 gap-4 text-xs">
                                <div>
                                    <div className="text-[10px] font-bold text-slate-400 uppercase mb-1">Status</div>
                                    <span className={cn(
                                        "font-bold uppercase px-2 py-0.5",
                                        selectedTask.status === 'Completed' ? "bg-emerald-100 text-emerald-700" :
                                        selectedTask.status === 'In Progress' ? "bg-blue-100 text-blue-700" :
                                        selectedTask.status === 'In Review' ? "bg-purple-100 text-purple-700" :
                                        "bg-amber-100 text-amber-700"
                                    )}>
                                        {selectedTask.status}
                                    </span>
                                </div>
                                <div>
                                    <div className="text-[10px] font-bold text-slate-400 uppercase mb-1">Due Date</div>
                                    <span className={cn("font-bold", isOverdue(selectedTask) ? "text-red-600" : "text-slate-700")}>
                                        {selectedTask.dueDate ? new Date(selectedTask.dueDate).toLocaleDateString() : 'No date'}
                                    </span>
                                </div>
                            </div>

                            {/* Notes */}
                            {selectedTask.notes && (
                                <div>
                                    <div className="text-[10px] font-bold text-slate-400 uppercase mb-1">Notes</div>
                                    <p className="text-xs text-slate-700 bg-slate-50 p-3 border border-slate-100">{selectedTask.notes}</p>
                                </div>
                            )}

                            {/* Auto-generated */}
                            {selectedTask.autoGenerated && (
                                <div className="flex items-center space-x-2 p-2 bg-orange-50 border border-orange-200">
                                    <Zap className="w-4 h-4 text-orange-500" />
                                    <span className="text-[10px] font-bold text-orange-700">Auto-generated: {selectedTask.triggerReason}</span>
                                </div>
                            )}

                            {/* Outcome */}
                            {selectedTask.status !== 'Completed' && (
                                <div>
                                    <div className="text-[10px] font-bold text-slate-400 uppercase mb-1">Outcome / Result</div>
                                    <textarea
                                        value={outcomeText}
                                        onChange={(e) => setOutcomeText(e.target.value)}
                                        placeholder="Describe the outcome of this task..."
                                        className="w-full px-3 py-2 text-sm border border-slate-200 focus:outline-none focus:border-black h-24 resize-none"
                                    />
                                </div>
                            )}
                        </div>

                        <div className="px-6 py-4 border-t border-slate-100 bg-slate-50 flex justify-between">
                            <div className="flex items-center space-x-2">
                                {selectedTask.status !== 'Completed' && (
                                    <>
                                        {selectedTask.status === 'To Do' && (
                                            <button
                                                onClick={async () => {
                                                    await handleUpdateTask(selectedTask._id, { status: 'In Progress' });
                                                    setIsModalOpen(false);
                                                    fetchAllColumns();
                                                }}
                                                className="flex items-center space-x-1 px-3 py-2 bg-blue-600 text-white text-xs font-bold uppercase hover:bg-blue-700"
                                            >
                                                <PlayCircle className="w-3.5 h-3.5" />
                                                <span>Start</span>
                                            </button>
                                        )}
                                        <button
                                            onClick={async () => {
                                                await handleUpdateTask(selectedTask._id, { status: 'Ignored' });
                                                setIsModalOpen(false);
                                                fetchAllColumns();
                                            }}
                                            className="flex items-center space-x-1 px-3 py-2 text-slate-500 hover:bg-slate-100 text-xs font-bold uppercase"
                                        >
                                            <SkipForward className="w-3.5 h-3.5" />
                                            <span>Ignore</span>
                                        </button>
                                    </>
                                )}
                            </div>
                            <div className="flex items-center space-x-2">
                                <button
                                    onClick={() => setIsModalOpen(false)}
                                    className="px-4 py-2 text-xs font-bold uppercase text-slate-500 hover:text-black"
                                >
                                    Close
                                </button>
                                {selectedTask.status !== 'Completed' && (
                                    <button
                                        onClick={handleCompleteTask}
                                        disabled={isSubmitting}
                                        className="px-6 py-2 bg-emerald-600 text-white text-xs font-bold uppercase hover:bg-emerald-700 disabled:opacity-50 flex items-center space-x-2"
                                    >
                                        {isSubmitting && <Loader2 className="w-3 h-3 animate-spin" />}
                                        <CheckCircle2 className="w-4 h-4" />
                                        <span>Complete</span>
                                    </button>
                                )}
                            </div>
                        </div>
                    </div>
                </div>
            )}

            {/* New Task Modal */}
            {isNewTaskModalOpen && (
                <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm p-4">
                    <div className="bg-white w-full max-w-md shadow-2xl animate-in fade-in zoom-in duration-200">
                        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-100">
                            <h2 className="text-sm font-black uppercase tracking-widest text-slate-900">New Retention Task</h2>
                            <button onClick={() => setIsNewTaskModalOpen(false)} className="text-slate-400 hover:text-black">
                                <X className="w-5 h-5" />
                            </button>
                        </div>

                        <form onSubmit={handleCreateTask} className="p-6 space-y-4">
                            <div>
                                <label className="text-[10px] font-bold text-slate-500 uppercase block mb-1">Client *</label>
                                <select
                                    required
                                    value={newTask.client}
                                    onChange={(e) => setNewTask({ ...newTask, client: e.target.value })}
                                    className="w-full px-3 py-2 border border-slate-200 text-sm focus:outline-none focus:border-black"
                                >
                                    <option value="">Select Client</option>
                                    {clients.map(c => (
                                        <option key={c._id} value={c._id}>{c.name}</option>
                                    ))}
                                </select>
                            </div>

                            <div className="grid grid-cols-2 gap-4">
                                <div>
                                    <label className="text-[10px] font-bold text-slate-500 uppercase block mb-1">Type</label>
                                    <select
                                        value={newTask.type}
                                        onChange={(e) => setNewTask({ ...newTask, type: e.target.value })}
                                        className="w-full px-3 py-2 border border-slate-200 text-sm focus:outline-none focus:border-black"
                                    >
                                        {['Followup Call', 'Followup Email', 'Check-in', 'Re-engagement', 'Win-back', 'Feedback Request', 'Upsell Opportunity'].map(t => (
                                            <option key={t} value={t}>{t}</option>
                                        ))}
                                    </select>
                                </div>
                                <div>
                                    <label className="text-[10px] font-bold text-slate-500 uppercase block mb-1">Priority</label>
                                    <select
                                        value={newTask.priority}
                                        onChange={(e) => setNewTask({ ...newTask, priority: e.target.value })}
                                        className="w-full px-3 py-2 border border-slate-200 text-sm focus:outline-none focus:border-black"
                                    >
                                        {['Low', 'Medium', 'High', 'Critical'].map(p => (
                                            <option key={p} value={p}>{p}</option>
                                        ))}
                                    </select>
                                </div>
                            </div>

                            <div className="grid grid-cols-2 gap-4">
                                <div>
                                    <label className="text-[10px] font-bold text-slate-500 uppercase block mb-1">Due Date</label>
                                    <input
                                        type="date"
                                        value={newTask.dueDate}
                                        onChange={(e) => setNewTask({ ...newTask, dueDate: e.target.value })}
                                        className="w-full px-3 py-2 border border-slate-200 text-sm focus:outline-none focus:border-black"
                                    />
                                </div>
                                <div>
                                    <label className="text-[10px] font-bold text-slate-500 uppercase block mb-1">Assign To</label>
                                    <select
                                        value={newTask.assignedTo}
                                        onChange={(e) => setNewTask({ ...newTask, assignedTo: e.target.value })}
                                        className="w-full px-3 py-2 border border-slate-200 text-sm focus:outline-none focus:border-black"
                                    >
                                        <option value="">Unassigned</option>
                                        {users.map(u => (
                                            <option key={u._id} value={u._id}>{u.firstName} {u.lastName}</option>
                                        ))}
                                    </select>
                                </div>
                            </div>

                            <div>
                                <label className="text-[10px] font-bold text-slate-500 uppercase block mb-1">Notes</label>
                                <textarea
                                    value={newTask.notes}
                                    onChange={(e) => setNewTask({ ...newTask, notes: e.target.value })}
                                    placeholder="Add any notes or context..."
                                    className="w-full px-3 py-2 border border-slate-200 text-sm focus:outline-none focus:border-black h-20 resize-none"
                                />
                            </div>

                            <div className="flex justify-end space-x-2 pt-4">
                                <button
                                    type="button"
                                    onClick={() => setIsNewTaskModalOpen(false)}
                                    className="px-4 py-2 text-xs font-bold uppercase text-slate-500 hover:text-black"
                                >
                                    Cancel
                                </button>
                                <button
                                    type="submit"
                                    disabled={isSubmitting}
                                    className="px-6 py-2 bg-black text-white text-xs font-bold uppercase hover:bg-slate-800 disabled:opacity-50 flex items-center space-x-2"
                                >
                                    {isSubmitting && <Loader2 className="w-3 h-3 animate-spin" />}
                                    <span>Create Task</span>
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            )}
        </div>
    );
}
