import mongoose from 'mongoose';

const RetentionTaskSchema = new mongoose.Schema({
    client: { type: String, ref: 'Client', required: true },
    type: { 
        type: String, 
        enum: ['Followup Call', 'Followup Email', 'Check-in', 'Re-engagement', 'Win-back', 'Feedback Request', 'Upsell Opportunity'], 
        required: true 
    },
    status: { 
        type: String, 
        enum: ['Pending', 'In Progress', 'Completed', 'Skipped', 'Overdue'], 
        default: 'Pending' 
    },
    priority: { 
        type: String, 
        enum: ['Low', 'Medium', 'High', 'Critical'], 
        default: 'Medium' 
    },
    dueDate: { type: Date, required: true },
    assignedTo: { type: String, ref: 'RXHQUsers' },
    notes: String,
    outcome: String,
    completedAt: Date,
    completedBy: { type: String, ref: 'RXHQUsers' },
    
    // Automation metadata
    autoGenerated: { type: Boolean, default: false },
    triggerReason: String, // e.g., "90 days inactive", "No orders in 60 days"
    
    createdAt: { type: Date, default: Date.now },
    updatedAt: { type: Date, default: Date.now }
});

RetentionTaskSchema.index({ client: 1, status: 1 });
RetentionTaskSchema.index({ assignedTo: 1, dueDate: 1 });
RetentionTaskSchema.index({ status: 1, dueDate: 1 });

export default mongoose.models.RetentionTask || mongoose.model('RetentionTask', RetentionTaskSchema);
