import mongoose from 'mongoose';

const RetentionTaskSchema = new mongoose.Schema({
    client: { type: mongoose.Schema.Types.ObjectId, ref: 'Client', required: true },
    task: String,
    type: { 
        type: String, 
        enum: ['Followup Call', 'Followup Email', 'Check-in', 'Re-engagement', 'Win-back', 'Feedback Request', 'Upsell Opportunity'], 
        required: true 
    },
    status: { 
        type: String, 
        enum: ['To Do', 'In Progress', 'In Review', 'Ignored', 'Completed'], 
        default: 'To Do' 
    },
    priority: { 
        type: String, 
        enum: ['Low', 'Medium', 'High', 'Critical'], 
        default: 'Medium' 
    },
    dueDate: Date,
    nextFollowupDate: Date,
    completionDate: Date,
    assignedTo: { type: String, ref: 'RXHQUsers' },
    notes: String,
    outcome: String,
    completedAt: Date,
    completedBy: { type: String, ref: 'RXHQUsers' },
    
    // Automation metadata
    autoGenerated: { type: Boolean, default: false },
    triggerReason: String,
    
    createdBy: String,
    createdAt: { type: Date, default: Date.now },
    updatedAt: { type: Date, default: Date.now }
});

RetentionTaskSchema.index({ client: 1, status: 1 });
RetentionTaskSchema.index({ assignedTo: 1, dueDate: 1 });
RetentionTaskSchema.index({ status: 1, dueDate: 1 });

export default mongoose.models.RetentionTask || mongoose.model('RetentionTask', RetentionTaskSchema);
