import mongoose from 'mongoose';

const SkuSchema = new mongoose.Schema({
    _id: { type: String, default: () => new mongoose.Types.ObjectId().toString() }, // Mapped from 'sku' or auto-generated
    name: { type: String, required: true },
    image: String,
    category: String,
    subCategory: String,
    materialType: String,
    uom: String,
    salePrice: Number,
    orderUpto: Number,
    reOrderPoint: Number,
    kitApplied: { type: Boolean, default: false },
    isLotApplied: { type: Boolean, default: false },
    isWebProduct: { type: Boolean, default: false },
    website: String, 
    // WooCommerce Specific Fields
    webId: Number,
    slug: String,
    permalink: String,
    dateCreated: Date,
    dateModified: Date,
    type: { type: String, default: 'simple' },
    status: String,
    featured: Boolean,
    catalogVisibility: String,
    description: String,
    shortDescription: String,
    sku_code: String, // To avoid collision with our _id if needed
    price: Number,
    regularPrice: Number,
    dateOnSaleFrom: Date,
    dateOnSaleTo: Date,
    onSale: Boolean,
    purchasable: Boolean,
    totalSales: Number,
    virtual: Boolean,
    downloadable: Boolean,
    taxStatus: String,
    taxClass: String,
    manageStock: Boolean,
    stockQuantity: Number,
    stockStatus: String,
    backorders: String,
    lowStockAmount: Number,
    soldIndividually: Boolean,
    weight: String,
    dimensions: {
        length: String,
        width: String,
        height: String
    },
    shippingRequired: Boolean,
    shippingTaxable: Boolean,
    shippingClass: String,
    reviewsAllowed: Boolean,
    averageRating: String,
    ratingCount: Number,
    upsellIds: [Number],
    crossSellIds: [Number],
    parentId: Number,
    tags: [mongoose.Schema.Types.Mixed],
    webCategories: [{
        id: Number,
        name: String,
        slug: String
    }],
    webImages: [{
        id: Number,
        src: String,
        name: String,
        alt: String,
        dateCreated: Date,
        dateModified: Date
    }],
    webAttributes: [mongoose.Schema.Types.Mixed],
    metaData: [mongoose.Schema.Types.Mixed],
    variances: [{
        _id: { type: String, default: () => new mongoose.Types.ObjectId().toString() },
        id: Number,
        name: String,
        website: String,
        image: String,
        sku: String,
        price: Number,
        regularPrice: Number,
        salePrice: Number,
        status: String,
        stockQuantity: Number,
        stockStatus: String,
        attributes: [mongoose.Schema.Types.Mixed],
        dateCreated: Date,
        dateModified: Date,
        permalink: String
    }],
    totalWebOrders: { type: Number, default: 0 },
    createdAt: { type: Date, default: Date.now },
    updatedAt: { type: Date, default: Date.now }
});

export default mongoose.models.Sku || mongoose.model('Sku', SkuSchema);
